### ISSUE TITLE
void * definition required in alloc.h

### ISSUE THREAD

**Issue by feilipu** [BleuLlama/bleu-romtools#1]
Using Ubuntu 16.04 AMD64, I found that the tools would not compile unless the definitions in [zcc/as/alloc.h](https://github.com/BleuLlama/bleu-romtools/blob/master/zcc/as/alloc.h) and [zcc/link/alloc.h](https://github.com/BleuLlama/bleu-romtools/blob/master/zcc/link/alloc.h) were modified to be
`extern void *`
rather than
`extern char *`

That may be a specific issue with the current GCC and lib version with Ubuntu.

**Comment by domschl** [comment]
On Arch Linux with GCC 6.2.1, I too had to change all alloc functions from char\* to void*:

diff --git a/zcc/link/alloc.h b/zcc/link/alloc.h
index fb0c407..5f98a3b 100644
--- a/zcc/link/alloc.h
+++ b/zcc/link/alloc.h
@@ -1,8 +1,7 @@
/\* alloc.h _/
/_ DECUS C */

extern  [-char-]{+void+}    *alloc();
extern  [-char-]{+void+}    *malloc();
extern  [-char-]{+void+}    *calloc();
extern  [-char-]{+void+}    *realloc();

and

diff --git a/zcc/as/alloc.h b/zcc/as/alloc.h
index e4f96b1..3858a90 100644
--- a/zcc/as/alloc.h
+++ b/zcc/as/alloc.h
@@ -1,10 +1,10 @@
/\* alloc.h _/
/_ DECUS C */

extern  [-char-]{+void+}    *alloc();
#ifndef **APPLE**
extern  [-char-]{+void+}    *malloc();
extern  [-char-]{+void+}    *calloc();
#endif
extern  [-char-]{+void+}    *realloc();

**Comment by BleuLlama** [comment]
Just fixed this.  I need to do more cleanups on linux in the future.
